/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.io.IOException;

import com.mycompany.practica1.modelos.ManejadorApuestas;
import com.mycompany.practica1.modelos.ManejadorReportes;
import com.mycompany.practica1.modelos.ModelCarreras;
import com.mycompany.practica1.modelos.Reporte;

/**
 *
 * @author fernanrod
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }
    ManejadorApuestas manejadorApuestas;        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        carrerasPanel = new javax.swing.JPanel();
        realizarCarreraButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordenCaballosTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        reportesPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultadosPunteoTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultadosNombreTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tiempoPromedioVerificacionLabel = new javax.swing.JLabel();
        pasosPromedioVerificacionLabel = new javax.swing.JLabel();
        mayorPasosVerificacionLabel = new javax.swing.JLabel();
        menorPasosVerificacionLabel = new javax.swing.JLabel();
        tiempoPromedioOrdenamientoPunteoLabel = new javax.swing.JLabel();
        pasosPromedioOrdenamientoPunteoLabel = new javax.swing.JLabel();
        tiempoPromedioResultadosLabel = new javax.swing.JLabel();
        pasosPromedioResultadosLabel = new javax.swing.JLabel();
        mayorPasosResultadosLabel = new javax.swing.JLabel();
        menorPasosResultadosLabel = new javax.swing.JLabel();
        tiempoPromedioOrdenamientoNombreLabel = new javax.swing.JLabel();
        pasosPromedioOrdenamientoNombreLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        cargarApuestasMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        realizarCarreraButton.setText("Realizar Carrera");
        realizarCarreraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarCarreraButtonActionPerformed(evt);
            }
        });

        ordenCaballosTextArea.setEditable(false);
        ordenCaballosTextArea.setColumns(20);
        ordenCaballosTextArea.setRows(5);
        jScrollPane1.setViewportView(ordenCaballosTextArea);

        jLabel1.setText("Resultados Caballos Carrera:");

        javax.swing.GroupLayout carrerasPanelLayout = new javax.swing.GroupLayout(carrerasPanel);
        carrerasPanel.setLayout(carrerasPanelLayout);
        carrerasPanelLayout.setHorizontalGroup(
            carrerasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carrerasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(realizarCarreraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(carrerasPanelLayout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel1)
                .addContainerGap(296, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carrerasPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        carrerasPanelLayout.setVerticalGroup(
            carrerasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carrerasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(realizarCarreraButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Carreras", carrerasPanel);

        jLabel2.setText("Resultados por Punteo:");

        jLabel3.setText("Resultados por Nombre:");

        resultadosPunteoTextArea.setEditable(false);
        resultadosPunteoTextArea.setColumns(20);
        resultadosPunteoTextArea.setRows(5);
        jScrollPane2.setViewportView(resultadosPunteoTextArea);

        resultadosNombreTextArea.setEditable(false);
        resultadosNombreTextArea.setColumns(20);
        resultadosNombreTextArea.setRows(5);
        jScrollPane3.setViewportView(resultadosNombreTextArea);

        jLabel4.setText("Reportes de Rendimiento");

        jLabel5.setText("Tiempo Promedio:");

        jLabel6.setText("Cantidad de Pasos Promedio:");

        jLabel7.setText("Verificacion de Apuestas");

        jLabel8.setText("Calculo de Resultados");

        jLabel9.setText("Tiempo Promedio:");

        jLabel10.setText("Cantidad de Pasos Promedio:");

        jLabel11.setText("Mayor Cantidad de Pasos:");

        jLabel12.setText("Mayor Cantidad de Pasos:");

        jLabel13.setText("Menor Cantidad de Pasos:");

        jLabel14.setText("Menor Cantidad de Pasos:");

        jLabel15.setText("Ordenamiento por Punteo");

        jLabel16.setText("Ordenamiento por Nombre");

        jLabel17.setText("Tiempo Promedio:");

        jLabel18.setText("Cantidad de Pasos Promedio:");

        jLabel21.setText("Tiempo Promedio:");

        jLabel22.setText("Cantidad de Pasos Promedio:");

        tiempoPromedioVerificacionLabel.setText("jLabel25");

        pasosPromedioVerificacionLabel.setText("jLabel26");

        mayorPasosVerificacionLabel.setText("jLabel27");

        menorPasosVerificacionLabel.setText("jLabel28");

        tiempoPromedioOrdenamientoPunteoLabel.setText("jLabel29");

        pasosPromedioOrdenamientoPunteoLabel.setText("jLabel30");

        tiempoPromedioResultadosLabel.setText("jLabel33");

        pasosPromedioResultadosLabel.setText("jLabel34");

        mayorPasosResultadosLabel.setText("jLabel35");

        menorPasosResultadosLabel.setText("jLabel36");

        tiempoPromedioOrdenamientoNombreLabel.setText("jLabel38");

        pasosPromedioOrdenamientoNombreLabel.setText("jLabel39");

        javax.swing.GroupLayout reportesPanelLayout = new javax.swing.GroupLayout(reportesPanel);
        reportesPanel.setLayout(reportesPanelLayout);
        reportesPanelLayout.setHorizontalGroup(
            reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportesPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap())
                    .addGroup(reportesPanelLayout.createSequentialGroup()
                        .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(reportesPanelLayout.createSequentialGroup()
                                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(reportesPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pasosPromedioVerificacionLabel)
                                        .addGap(75, 75, 75))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, reportesPanelLayout.createSequentialGroup()
                                        .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, reportesPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tiempoPromedioVerificacionLabel))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(reportesPanelLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addGroup(reportesPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mayorPasosResultadosLabel))
                                            .addGroup(reportesPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(menorPasosResultadosLabel))
                                            .addGroup(reportesPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pasosPromedioResultadosLabel))
                                            .addGroup(reportesPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tiempoPromedioResultadosLabel))))
                                    .addGroup(reportesPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pasosPromedioOrdenamientoNombreLabel))
                                    .addGroup(reportesPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tiempoPromedioOrdenamientoNombreLabel))))
                            .addGroup(reportesPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(103, 103, 103))
                            .addGroup(reportesPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menorPasosVerificacionLabel)
                                .addGap(461, 461, 461)))
                        .addGap(32, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportesPanelLayout.createSequentialGroup()
                        .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reportesPanelLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pasosPromedioOrdenamientoPunteoLabel))
                            .addGroup(reportesPanelLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tiempoPromedioOrdenamientoPunteoLabel))
                            .addComponent(jLabel15)
                            .addGroup(reportesPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mayorPasosVerificacionLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(292, 292, 292))
        );
        reportesPanelLayout.setVerticalGroup(
            reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tiempoPromedioVerificacionLabel)
                    .addComponent(jLabel9)
                    .addComponent(tiempoPromedioResultadosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pasosPromedioVerificacionLabel)
                    .addComponent(jLabel10)
                    .addComponent(pasosPromedioResultadosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mayorPasosVerificacionLabel)
                    .addComponent(jLabel12)
                    .addComponent(mayorPasosResultadosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(menorPasosVerificacionLabel)
                    .addComponent(jLabel14)
                    .addComponent(menorPasosResultadosLabel))
                .addGap(18, 18, 18)
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tiempoPromedioOrdenamientoPunteoLabel)
                    .addComponent(jLabel21)
                    .addComponent(tiempoPromedioOrdenamientoNombreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(pasosPromedioOrdenamientoPunteoLabel)
                    .addComponent(jLabel22)
                    .addComponent(pasosPromedioOrdenamientoNombreLabel))
                .addGap(64, 64, 64))
        );

        mainTabbedPane.addTab("Reportes", reportesPanel);

        archivoMenu.setText("Archivo");

        cargarApuestasMenuItem.setText("Cargar Apuestas");
        cargarApuestasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarApuestasMenuItemActionPerformed(evt);
            }
        });
        archivoMenu.add(cargarApuestasMenuItem);

        jMenuBar1.add(archivoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void realizarCarreraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarCarreraButtonActionPerformed
        // TODO add your handling code here:
        ModelCarreras.realizarCarrera();
        for (int i = 0; i < ModelCarreras.getPosicionesFinales().length; i++) {
            ordenCaballosTextArea.setText(ordenCaballosTextArea.getText()+(i+1)+". Caballo No."+ModelCarreras.getPosicionesFinales()[i]+"\n");
        }
        
        ModelCarreras.verificarResultados();
        ModelCarreras.getApuestasAprobadas().ordenarPorPunteo();
        ModelCarreras.getApuestasAprobadas().imprimirFinalAPrincipio(resultadosPunteoTextArea);
        ModelCarreras.getApuestasAprobadas().ordenarAlfabeticamente();
        ModelCarreras.getApuestasAprobadas().imprimirPrincipioAFinal(resultadosNombreTextArea);
        
        Reporte reporteVerificacion = ManejadorReportes.getReporteVerificacionApuesta();
        Reporte reporteCalculoResultados = ManejadorReportes.getReporteCalculoResultados();
        Reporte reporteOrdenamientoNombre = ManejadorReportes.getReporteOrdenamientoAlfabetico();
        Reporte reporteOrdenamientoPunteo = ManejadorReportes.getReporteOrdenamientoPunteo();
        
        tiempoPromedioVerificacionLabel.setText(String.valueOf(reporteVerificacion.getTiempoPromedio())+" nanos");
        pasosPromedioVerificacionLabel.setText(String.valueOf(reporteVerificacion.getPasosPromedio())+" pasos");
        mayorPasosVerificacionLabel.setText(String.valueOf(reporteVerificacion.getMayorCantidadPasos())+" pasos");
        menorPasosVerificacionLabel.setText(String.valueOf(reporteVerificacion.getMenorCantidadPasos())+" pasos");
        
        tiempoPromedioResultadosLabel.setText(String.valueOf(reporteCalculoResultados.getTiempoPromedio())+" nanos");
        pasosPromedioResultadosLabel.setText(String.valueOf(reporteCalculoResultados.getPasosPromedio())+" pasos");
        mayorPasosResultadosLabel.setText(String.valueOf(reporteCalculoResultados.getMayorCantidadPasos())+" pasos");
        menorPasosResultadosLabel.setText(String.valueOf(reporteCalculoResultados.getMenorCantidadPasos())+" pasos");

        tiempoPromedioOrdenamientoPunteoLabel.setText(String.valueOf(reporteOrdenamientoPunteo.getTiempoPromedio())+" nanos");
        pasosPromedioOrdenamientoPunteoLabel.setText(String.valueOf(reporteOrdenamientoPunteo.getPasosPromedio())+" pasos");

        tiempoPromedioOrdenamientoNombreLabel.setText(String.valueOf(reporteOrdenamientoNombre.getTiempoPromedio())+" nanos");
        pasosPromedioOrdenamientoNombreLabel.setText(String.valueOf(reporteOrdenamientoNombre.getPasosPromedio())+" pasos");
        
        javax.swing.JOptionPane.showMessageDialog(this, "Se ha realizado la carrera, puedes revisar los resultados en la seccion de reportes");
    }//GEN-LAST:event_realizarCarreraButtonActionPerformed

    private void cargarApuestasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarApuestasMenuItemActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.showOpenDialog(this);
        
        java.nio.file.Path archivo = fileChooser.getSelectedFile().toPath();
        manejadorApuestas = new ManejadorApuestas();
        try {
            ModelCarreras.cargarApuestas(archivo);
            javax.swing.JOptionPane.showMessageDialog(this, "Las apuestas han sido ingresadas y verificadas, puedes iniciar la carrera.\n"+
                                                            "Se ha creado un archivo con las apuestas rechazadas en:\n"+
                                                            System.getProperty("user.home")+"/apuestas_rechazadas.txt");
            realizarCarreraButton.setEnabled(true);
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ha ocurrido un error al abrir el archivo");
            realizarCarreraButton.setEnabled(false);
            e.printStackTrace();
        }
    }//GEN-LAST:event_cargarApuestasMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JMenuItem cargarApuestasMenuItem;
    private javax.swing.JPanel carrerasPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JLabel mayorPasosResultadosLabel;
    private javax.swing.JLabel mayorPasosVerificacionLabel;
    private javax.swing.JLabel menorPasosResultadosLabel;
    private javax.swing.JLabel menorPasosVerificacionLabel;
    private javax.swing.JTextArea ordenCaballosTextArea;
    private javax.swing.JLabel pasosPromedioOrdenamientoNombreLabel;
    private javax.swing.JLabel pasosPromedioOrdenamientoPunteoLabel;
    private javax.swing.JLabel pasosPromedioResultadosLabel;
    private javax.swing.JLabel pasosPromedioVerificacionLabel;
    private javax.swing.JButton realizarCarreraButton;
    private javax.swing.JPanel reportesPanel;
    private javax.swing.JTextArea resultadosNombreTextArea;
    private javax.swing.JTextArea resultadosPunteoTextArea;
    private javax.swing.JLabel tiempoPromedioOrdenamientoNombreLabel;
    private javax.swing.JLabel tiempoPromedioOrdenamientoPunteoLabel;
    private javax.swing.JLabel tiempoPromedioResultadosLabel;
    private javax.swing.JLabel tiempoPromedioVerificacionLabel;
    // End of variables declaration//GEN-END:variables
}
